import express from 'express';
import dotenv from "dotenv";
import routers from "#routers/_routers.js";
import viewRouters from "#routers/_viewRouters.js";
import cors from "cors";
dotenv.config();
const app = express();
app.use(express.static("public"));
app.use(cors({ origin: "*" }));
app.use(express.json());
app.set("view engine", "ejs");
app.use("/", viewRouters);
app.use("/api", routers);
export default app;
